# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SensePrice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SensePrice
pod 'EmptyDataSet-Swift', '~> 4.2.0'
pod 'NVActivityIndicatorView'
pod 'PMSuperButton'
pod 'SwiftyJSON', '~> 4.0'
pod 'Alamofire', '~> 4.5'

  target 'SensePriceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
